/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers"
import type { Provider } from "@ethersproject/providers"
import type {
    IVestingScheduler,
    IVestingSchedulerInterface
} from "../../../src/interface/IVestingScheduler"

const _abi = [
    {
        inputs: [],
        name: "AccountInvalid",
        type: "error"
    },
    {
        inputs: [],
        name: "CliffInvalid",
        type: "error"
    },
    {
        inputs: [],
        name: "FlowRateInvalid",
        type: "error"
    },
    {
        inputs: [],
        name: "HostInvalid",
        type: "error"
    },
    {
        inputs: [],
        name: "ScheduleAlreadyExists",
        type: "error"
    },
    {
        inputs: [],
        name: "ScheduleDoesNotExist",
        type: "error"
    },
    {
        inputs: [],
        name: "ScheduleNotFlowing",
        type: "error"
    },
    {
        inputs: [],
        name: "TimeWindowInvalid",
        type: "error"
    },
    {
        inputs: [],
        name: "ZeroAddress",
        type: "error"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "cliffAndFlowDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "int96",
                name: "flowRate",
                type: "int96"
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "cliffAmount",
                type: "uint256"
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "flowDelayCompensation",
                type: "uint256"
            }
        ],
        name: "VestingCliffAndFlowExecuted",
        type: "event"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "earlyEndCompensation",
                type: "uint256"
            },
            {
                indexed: false,
                internalType: "bool",
                name: "didCompensationFail",
                type: "bool"
            }
        ],
        name: "VestingEndExecuted",
        type: "event"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            }
        ],
        name: "VestingEndFailed",
        type: "event"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "startDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "cliffDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "int96",
                name: "flowRate",
                type: "int96"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "uint256",
                name: "cliffAmount",
                type: "uint256"
            }
        ],
        name: "VestingScheduleCreated",
        type: "event"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            }
        ],
        name: "VestingScheduleDeleted",
        type: "event"
    },
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                indexed: true,
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "oldEndDate",
                type: "uint32"
            },
            {
                indexed: false,
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            }
        ],
        name: "VestingScheduleUpdated",
        type: "event"
    },
    {
        inputs: [
            {
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                internalType: "uint32",
                name: "startDate",
                type: "uint32"
            },
            {
                internalType: "uint32",
                name: "cliffDate",
                type: "uint32"
            },
            {
                internalType: "int96",
                name: "flowRate",
                type: "int96"
            },
            {
                internalType: "uint256",
                name: "cliffAmount",
                type: "uint256"
            },
            {
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            },
            {
                internalType: "bytes",
                name: "ctx",
                type: "bytes"
            }
        ],
        name: "createVestingSchedule",
        outputs: [
            {
                internalType: "bytes",
                name: "newCtx",
                type: "bytes"
            }
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                internalType: "bytes",
                name: "ctx",
                type: "bytes"
            }
        ],
        name: "deleteVestingSchedule",
        outputs: [
            {
                internalType: "bytes",
                name: "newCtx",
                type: "bytes"
            }
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            }
        ],
        name: "executeCliffAndFlow",
        outputs: [
            {
                internalType: "bool",
                name: "success",
                type: "bool"
            }
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            }
        ],
        name: "executeEndVesting",
        outputs: [
            {
                internalType: "bool",
                name: "success",
                type: "bool"
            }
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "sender",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            }
        ],
        name: "getVestingSchedule",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint32",
                        name: "cliffAndFlowDate",
                        type: "uint32"
                    },
                    {
                        internalType: "uint32",
                        name: "endDate",
                        type: "uint32"
                    },
                    {
                        internalType: "int96",
                        name: "flowRate",
                        type: "int96"
                    },
                    {
                        internalType: "uint256",
                        name: "cliffAmount",
                        type: "uint256"
                    }
                ],
                internalType: "struct IVestingScheduler.VestingSchedule",
                name: "",
                type: "tuple"
            }
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "contract ISuperToken",
                name: "superToken",
                type: "address"
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address"
            },
            {
                internalType: "uint32",
                name: "endDate",
                type: "uint32"
            },
            {
                internalType: "bytes",
                name: "ctx",
                type: "bytes"
            }
        ],
        name: "updateVestingSchedule",
        outputs: [
            {
                internalType: "bytes",
                name: "newCtx",
                type: "bytes"
            }
        ],
        stateMutability: "nonpayable",
        type: "function"
    }
] as const

export class IVestingScheduler__factory {
    static readonly abi = _abi
    static createInterface(): IVestingSchedulerInterface {
        return new utils.Interface(_abi) as IVestingSchedulerInterface
    }
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): IVestingScheduler {
        return new Contract(
            address,
            _abi,
            signerOrProvider
        ) as IVestingScheduler
    }
}
