/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as typesSol from "./Types.sol";
export type { typesSol };
export type { AutomateReady } from "./AutomateReady";
export type { AutomateTaskCreator } from "./AutomateTaskCreator";
