/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConstantOutflowNFT,
  IConstantOutflowNFTInterface,
} from "../../../../../../@superfluid-finance/ethereum-contracts/contracts/interfaces/superfluid/IConstantOutflowNFT";

const _abi = [
  {
    inputs: [],
    name: "CFA_NFT_APPROVE_CALLER_NOT_OWNER_OR_APPROVED_FOR_ALL",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_APPROVE_TO_CALLER",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_APPROVE_TO_CURRENT_OWNER",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_INVALID_TOKEN_ID",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_ONLY_SUPER_TOKEN_FACTORY",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_TRANSFER_CALLER_NOT_OWNER_OR_APPROVED_FOR_ALL",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_TRANSFER_FROM_INCORRECT_OWNER",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_TRANSFER_IS_NOT_ALLOWED",
    type: "error",
  },
  {
    inputs: [],
    name: "CFA_NFT_TRANSFER_TO_ZERO_ADDRESS",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_INVALID_SUPER_TOKEN",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_MINT_TO_AND_FLOW_RECEIVER_SAME",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_MINT_TO_ZERO_ADDRESS",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_ONLY_CONSTANT_INFLOW",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_ONLY_FLOW_AGREEMENTS",
    type: "error",
  },
  {
    inputs: [],
    name: "COF_NFT_TOKEN_ALREADY_EXISTS",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "MetadataUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "flowDataByTokenId",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "superToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "flowSender",
            type: "address",
          },
          {
            internalType: "address",
            name: "flowReceiver",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "flowStartDate",
            type: "uint32",
          },
        ],
        internalType: "struct IFlowNFTBase.FlowNFTData",
        name: "flowData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getApproved",
    outputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "superToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowReceiver",
        type: "address",
      },
    ],
    name: "getTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "nftName",
        type: "string",
      },
      {
        internalType: "string",
        name: "nftSymbol",
        type: "string",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "isApprovedForAll",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISuperfluidToken",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowReceiver",
        type: "address",
      },
    ],
    name: "onCreate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISuperfluidToken",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowReceiver",
        type: "address",
      },
    ],
    name: "onDelete",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISuperfluidToken",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowSender",
        type: "address",
      },
      {
        internalType: "address",
        name: "flowReceiver",
        type: "address",
      },
    ],
    name: "onUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "triggerMetadataUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConstantOutflowNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IConstantOutflowNFTInterface {
    return new utils.Interface(_abi) as IConstantOutflowNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConstantOutflowNFT {
    return new Contract(address, _abi, signerOrProvider) as IConstantOutflowNFT;
  }
}
