/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gelato from "./gelato";
export type { gelato };
import type * as interface from "./interface";
export type { interface };
export type { VestingAutomation } from "./VestingAutomation";
export type { VestingScheduler } from "./VestingScheduler";
