/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils
} from "ethers"
import type {
    FunctionFragment,
    Result,
    EventFragment
} from "@ethersproject/abi"
import type { Listener, Provider } from "@ethersproject/providers"
import type {
    TypedEventFilter,
    TypedEvent,
    TypedListener,
    OnEvent,
    PromiseOrValue
} from "../common"

export declare namespace IVestingScheduler {
    export type VestingScheduleStruct = {
        cliffAndFlowDate: PromiseOrValue<BigNumberish>
        endDate: PromiseOrValue<BigNumberish>
        flowRate: PromiseOrValue<BigNumberish>
        cliffAmount: PromiseOrValue<BigNumberish>
    }

    export type VestingScheduleStructOutput = [
        number,
        number,
        BigNumber,
        BigNumber
    ] & {
        cliffAndFlowDate: number
        endDate: number
        flowRate: BigNumber
        cliffAmount: BigNumber
    }
}

export interface VestingSchedulerInterface extends utils.Interface {
    functions: {
        "END_DATE_VALID_BEFORE()": FunctionFragment
        "MIN_VESTING_DURATION()": FunctionFragment
        "START_DATE_VALID_AFTER()": FunctionFragment
        "afterAgreementCreated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment
        "afterAgreementTerminated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment
        "afterAgreementUpdated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment
        "beforeAgreementCreated(address,address,bytes32,bytes,bytes)": FunctionFragment
        "beforeAgreementTerminated(address,address,bytes32,bytes,bytes)": FunctionFragment
        "beforeAgreementUpdated(address,address,bytes32,bytes,bytes)": FunctionFragment
        "cfaV1()": FunctionFragment
        "createVestingSchedule(address,address,uint32,uint32,int96,uint256,uint32,bytes)": FunctionFragment
        "deleteVestingSchedule(address,address,bytes)": FunctionFragment
        "executeCliffAndFlow(address,address,address)": FunctionFragment
        "executeEndVesting(address,address,address)": FunctionFragment
        "getVestingSchedule(address,address,address)": FunctionFragment
        "updateVestingSchedule(address,address,uint32,bytes)": FunctionFragment
        "vestingSchedules(bytes32)": FunctionFragment
    }

    getFunction(
        nameOrSignatureOrTopic:
            | "END_DATE_VALID_BEFORE"
            | "MIN_VESTING_DURATION"
            | "START_DATE_VALID_AFTER"
            | "afterAgreementCreated"
            | "afterAgreementTerminated"
            | "afterAgreementUpdated"
            | "beforeAgreementCreated"
            | "beforeAgreementTerminated"
            | "beforeAgreementUpdated"
            | "cfaV1"
            | "createVestingSchedule"
            | "deleteVestingSchedule"
            | "executeCliffAndFlow"
            | "executeEndVesting"
            | "getVestingSchedule"
            | "updateVestingSchedule"
            | "vestingSchedules"
    ): FunctionFragment

    encodeFunctionData(
        functionFragment: "END_DATE_VALID_BEFORE",
        values?: undefined
    ): string
    encodeFunctionData(
        functionFragment: "MIN_VESTING_DURATION",
        values?: undefined
    ): string
    encodeFunctionData(
        functionFragment: "START_DATE_VALID_AFTER",
        values?: undefined
    ): string
    encodeFunctionData(
        functionFragment: "afterAgreementCreated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "afterAgreementTerminated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "afterAgreementUpdated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "beforeAgreementCreated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "beforeAgreementTerminated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "beforeAgreementUpdated",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(functionFragment: "cfaV1", values?: undefined): string
    encodeFunctionData(
        functionFragment: "createVestingSchedule",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "deleteVestingSchedule",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "executeCliffAndFlow",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<string>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "executeEndVesting",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<string>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "getVestingSchedule",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<string>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "updateVestingSchedule",
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>
        ]
    ): string
    encodeFunctionData(
        functionFragment: "vestingSchedules",
        values: [PromiseOrValue<BytesLike>]
    ): string

    decodeFunctionResult(
        functionFragment: "END_DATE_VALID_BEFORE",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "MIN_VESTING_DURATION",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "START_DATE_VALID_AFTER",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "afterAgreementCreated",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "afterAgreementTerminated",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "afterAgreementUpdated",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "beforeAgreementCreated",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "beforeAgreementTerminated",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "beforeAgreementUpdated",
        data: BytesLike
    ): Result
    decodeFunctionResult(functionFragment: "cfaV1", data: BytesLike): Result
    decodeFunctionResult(
        functionFragment: "createVestingSchedule",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "deleteVestingSchedule",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "executeCliffAndFlow",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "executeEndVesting",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "getVestingSchedule",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "updateVestingSchedule",
        data: BytesLike
    ): Result
    decodeFunctionResult(
        functionFragment: "vestingSchedules",
        data: BytesLike
    ): Result

    events: {
        "VestingCliffAndFlowExecuted(address,address,address,uint32,int96,uint256,uint256)": EventFragment
        "VestingEndExecuted(address,address,address,uint32,uint256,bool)": EventFragment
        "VestingEndFailed(address,address,address,uint32)": EventFragment
        "VestingScheduleCreated(address,address,address,uint32,uint32,int96,uint32,uint256)": EventFragment
        "VestingScheduleDeleted(address,address,address)": EventFragment
        "VestingScheduleUpdated(address,address,address,uint32,uint32)": EventFragment
    }

    getEvent(
        nameOrSignatureOrTopic: "VestingCliffAndFlowExecuted"
    ): EventFragment
    getEvent(nameOrSignatureOrTopic: "VestingEndExecuted"): EventFragment
    getEvent(nameOrSignatureOrTopic: "VestingEndFailed"): EventFragment
    getEvent(nameOrSignatureOrTopic: "VestingScheduleCreated"): EventFragment
    getEvent(nameOrSignatureOrTopic: "VestingScheduleDeleted"): EventFragment
    getEvent(nameOrSignatureOrTopic: "VestingScheduleUpdated"): EventFragment
}

export interface VestingCliffAndFlowExecutedEventObject {
    superToken: string
    sender: string
    receiver: string
    cliffAndFlowDate: number
    flowRate: BigNumber
    cliffAmount: BigNumber
    flowDelayCompensation: BigNumber
}
export type VestingCliffAndFlowExecutedEvent = TypedEvent<
    [string, string, string, number, BigNumber, BigNumber, BigNumber],
    VestingCliffAndFlowExecutedEventObject
>

export type VestingCliffAndFlowExecutedEventFilter =
    TypedEventFilter<VestingCliffAndFlowExecutedEvent>

export interface VestingEndExecutedEventObject {
    superToken: string
    sender: string
    receiver: string
    endDate: number
    earlyEndCompensation: BigNumber
    didCompensationFail: boolean
}
export type VestingEndExecutedEvent = TypedEvent<
    [string, string, string, number, BigNumber, boolean],
    VestingEndExecutedEventObject
>

export type VestingEndExecutedEventFilter =
    TypedEventFilter<VestingEndExecutedEvent>

export interface VestingEndFailedEventObject {
    superToken: string
    sender: string
    receiver: string
    endDate: number
}
export type VestingEndFailedEvent = TypedEvent<
    [string, string, string, number],
    VestingEndFailedEventObject
>

export type VestingEndFailedEventFilter =
    TypedEventFilter<VestingEndFailedEvent>

export interface VestingScheduleCreatedEventObject {
    superToken: string
    sender: string
    receiver: string
    startDate: number
    cliffDate: number
    flowRate: BigNumber
    endDate: number
    cliffAmount: BigNumber
}
export type VestingScheduleCreatedEvent = TypedEvent<
    [string, string, string, number, number, BigNumber, number, BigNumber],
    VestingScheduleCreatedEventObject
>

export type VestingScheduleCreatedEventFilter =
    TypedEventFilter<VestingScheduleCreatedEvent>

export interface VestingScheduleDeletedEventObject {
    superToken: string
    sender: string
    receiver: string
}
export type VestingScheduleDeletedEvent = TypedEvent<
    [string, string, string],
    VestingScheduleDeletedEventObject
>

export type VestingScheduleDeletedEventFilter =
    TypedEventFilter<VestingScheduleDeletedEvent>

export interface VestingScheduleUpdatedEventObject {
    superToken: string
    sender: string
    receiver: string
    oldEndDate: number
    endDate: number
}
export type VestingScheduleUpdatedEvent = TypedEvent<
    [string, string, string, number, number],
    VestingScheduleUpdatedEventObject
>

export type VestingScheduleUpdatedEventFilter =
    TypedEventFilter<VestingScheduleUpdatedEvent>

export interface VestingScheduler extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: VestingSchedulerInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(
        eventFilter?: TypedEventFilter<TEvent>
    ): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(
        eventFilter: TypedEventFilter<TEvent>
    ): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        END_DATE_VALID_BEFORE(overrides?: CallOverrides): Promise<[number]>

        MIN_VESTING_DURATION(overrides?: CallOverrides): Promise<[number]>

        START_DATE_VALID_AFTER(overrides?: CallOverrides): Promise<[number]>

        afterAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        afterAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        afterAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        beforeAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<[string]>

        beforeAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<[string]>

        beforeAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<[string]>

        cfaV1(
            overrides?: CallOverrides
        ): Promise<[string, string] & { host: string; cfa: string }>

        createVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            startDate: PromiseOrValue<BigNumberish>,
            cliffDate: PromiseOrValue<BigNumberish>,
            flowRate: PromiseOrValue<BigNumberish>,
            cliffAmount: PromiseOrValue<BigNumberish>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        deleteVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        executeCliffAndFlow(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        executeEndVesting(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        getVestingSchedule(
            supertoken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<[IVestingScheduler.VestingScheduleStructOutput]>

        updateVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        vestingSchedules(
            arg0: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<
            [number, number, BigNumber, BigNumber] & {
                cliffAndFlowDate: number
                endDate: number
                flowRate: BigNumber
                cliffAmount: BigNumber
            }
        >
    }

    END_DATE_VALID_BEFORE(overrides?: CallOverrides): Promise<number>

    MIN_VESTING_DURATION(overrides?: CallOverrides): Promise<number>

    START_DATE_VALID_AFTER(overrides?: CallOverrides): Promise<number>

    afterAgreementCreated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        arg5: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    afterAgreementTerminated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        arg5: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    afterAgreementUpdated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        arg5: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    beforeAgreementCreated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        overrides?: CallOverrides
    ): Promise<string>

    beforeAgreementTerminated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        overrides?: CallOverrides
    ): Promise<string>

    beforeAgreementUpdated(
        arg0: PromiseOrValue<string>,
        arg1: PromiseOrValue<string>,
        arg2: PromiseOrValue<BytesLike>,
        arg3: PromiseOrValue<BytesLike>,
        arg4: PromiseOrValue<BytesLike>,
        overrides?: CallOverrides
    ): Promise<string>

    cfaV1(
        overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; cfa: string }>

    createVestingSchedule(
        superToken: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        startDate: PromiseOrValue<BigNumberish>,
        cliffDate: PromiseOrValue<BigNumberish>,
        flowRate: PromiseOrValue<BigNumberish>,
        cliffAmount: PromiseOrValue<BigNumberish>,
        endDate: PromiseOrValue<BigNumberish>,
        ctx: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    deleteVestingSchedule(
        superToken: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        ctx: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    executeCliffAndFlow(
        superToken: PromiseOrValue<string>,
        sender: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    executeEndVesting(
        superToken: PromiseOrValue<string>,
        sender: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    getVestingSchedule(
        supertoken: PromiseOrValue<string>,
        sender: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        overrides?: CallOverrides
    ): Promise<IVestingScheduler.VestingScheduleStructOutput>

    updateVestingSchedule(
        superToken: PromiseOrValue<string>,
        receiver: PromiseOrValue<string>,
        endDate: PromiseOrValue<BigNumberish>,
        ctx: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    vestingSchedules(
        arg0: PromiseOrValue<BytesLike>,
        overrides?: CallOverrides
    ): Promise<
        [number, number, BigNumber, BigNumber] & {
            cliffAndFlowDate: number
            endDate: number
            flowRate: BigNumber
            cliffAmount: BigNumber
        }
    >

    callStatic: {
        END_DATE_VALID_BEFORE(overrides?: CallOverrides): Promise<number>

        MIN_VESTING_DURATION(overrides?: CallOverrides): Promise<number>

        START_DATE_VALID_AFTER(overrides?: CallOverrides): Promise<number>

        afterAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        afterAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        afterAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        beforeAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        beforeAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        beforeAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        cfaV1(
            overrides?: CallOverrides
        ): Promise<[string, string] & { host: string; cfa: string }>

        createVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            startDate: PromiseOrValue<BigNumberish>,
            cliffDate: PromiseOrValue<BigNumberish>,
            flowRate: PromiseOrValue<BigNumberish>,
            cliffAmount: PromiseOrValue<BigNumberish>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        deleteVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        executeCliffAndFlow(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<boolean>

        executeEndVesting(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<boolean>

        getVestingSchedule(
            supertoken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<IVestingScheduler.VestingScheduleStructOutput>

        updateVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>

        vestingSchedules(
            arg0: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<
            [number, number, BigNumber, BigNumber] & {
                cliffAndFlowDate: number
                endDate: number
                flowRate: BigNumber
                cliffAmount: BigNumber
            }
        >
    }

    filters: {
        "VestingCliffAndFlowExecuted(address,address,address,uint32,int96,uint256,uint256)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            cliffAndFlowDate?: null,
            flowRate?: null,
            cliffAmount?: null,
            flowDelayCompensation?: null
        ): VestingCliffAndFlowExecutedEventFilter
        VestingCliffAndFlowExecuted(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            cliffAndFlowDate?: null,
            flowRate?: null,
            cliffAmount?: null,
            flowDelayCompensation?: null
        ): VestingCliffAndFlowExecutedEventFilter

        "VestingEndExecuted(address,address,address,uint32,uint256,bool)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            endDate?: null,
            earlyEndCompensation?: null,
            didCompensationFail?: null
        ): VestingEndExecutedEventFilter
        VestingEndExecuted(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            endDate?: null,
            earlyEndCompensation?: null,
            didCompensationFail?: null
        ): VestingEndExecutedEventFilter

        "VestingEndFailed(address,address,address,uint32)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            endDate?: null
        ): VestingEndFailedEventFilter
        VestingEndFailed(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            endDate?: null
        ): VestingEndFailedEventFilter

        "VestingScheduleCreated(address,address,address,uint32,uint32,int96,uint32,uint256)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            startDate?: null,
            cliffDate?: null,
            flowRate?: null,
            endDate?: null,
            cliffAmount?: null
        ): VestingScheduleCreatedEventFilter
        VestingScheduleCreated(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            startDate?: null,
            cliffDate?: null,
            flowRate?: null,
            endDate?: null,
            cliffAmount?: null
        ): VestingScheduleCreatedEventFilter

        "VestingScheduleDeleted(address,address,address)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null
        ): VestingScheduleDeletedEventFilter
        VestingScheduleDeleted(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null
        ): VestingScheduleDeletedEventFilter

        "VestingScheduleUpdated(address,address,address,uint32,uint32)"(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            oldEndDate?: null,
            endDate?: null
        ): VestingScheduleUpdatedEventFilter
        VestingScheduleUpdated(
            superToken?: PromiseOrValue<string> | null,
            sender?: PromiseOrValue<string> | null,
            receiver?: PromiseOrValue<string> | null,
            oldEndDate?: null,
            endDate?: null
        ): VestingScheduleUpdatedEventFilter
    }

    estimateGas: {
        END_DATE_VALID_BEFORE(overrides?: CallOverrides): Promise<BigNumber>

        MIN_VESTING_DURATION(overrides?: CallOverrides): Promise<BigNumber>

        START_DATE_VALID_AFTER(overrides?: CallOverrides): Promise<BigNumber>

        afterAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        afterAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        afterAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        beforeAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        beforeAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        beforeAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        cfaV1(overrides?: CallOverrides): Promise<BigNumber>

        createVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            startDate: PromiseOrValue<BigNumberish>,
            cliffDate: PromiseOrValue<BigNumberish>,
            flowRate: PromiseOrValue<BigNumberish>,
            cliffAmount: PromiseOrValue<BigNumberish>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        deleteVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        executeCliffAndFlow(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        executeEndVesting(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        getVestingSchedule(
            supertoken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        updateVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        vestingSchedules(
            arg0: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<BigNumber>
    }

    populateTransaction: {
        END_DATE_VALID_BEFORE(
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        MIN_VESTING_DURATION(
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        START_DATE_VALID_AFTER(
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        afterAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        afterAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        afterAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            arg5: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        beforeAgreementCreated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        beforeAgreementTerminated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        beforeAgreementUpdated(
            arg0: PromiseOrValue<string>,
            arg1: PromiseOrValue<string>,
            arg2: PromiseOrValue<BytesLike>,
            arg3: PromiseOrValue<BytesLike>,
            arg4: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        cfaV1(overrides?: CallOverrides): Promise<PopulatedTransaction>

        createVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            startDate: PromiseOrValue<BigNumberish>,
            cliffDate: PromiseOrValue<BigNumberish>,
            flowRate: PromiseOrValue<BigNumberish>,
            cliffAmount: PromiseOrValue<BigNumberish>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        deleteVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        executeCliffAndFlow(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        executeEndVesting(
            superToken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        getVestingSchedule(
            supertoken: PromiseOrValue<string>,
            sender: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        updateVestingSchedule(
            superToken: PromiseOrValue<string>,
            receiver: PromiseOrValue<string>,
            endDate: PromiseOrValue<BigNumberish>,
            ctx: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        vestingSchedules(
            arg0: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>
    }
}
