name: Build Examples

on:
    # trigger on git push
    push:
        paths:
            - "projects/**"
            - ".github/workflows/build-examples.yml" # might not need this
    # trigger manually
    workflow_dispatch:

jobs:
    build-foundry-example:
        name: Build Foundry Examples
        runs-on: ubuntu-latest
        strategy:
            # build all examples independently
            fail-fast: false
            matrix:
                project: ["money-streaming-intro-foundry"]
                install: ["clean-install"]
        steps:
            - uses: actions/checkout@v3
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly
            - name: Install, Build, and Test
              run: |
                  cd "projects/${{ matrix.project }}"
                  forge install
                  forge build
                  forge test
